export const SETTINGS = {
  MAIL: {
    EMAIL: 'chunosov.dmitrij@bk.ru',
    EMAIL_PASSWORD: 'AU4vPai3YmTSkcK6gshm',
  },
  ACCESS_TOKEN_STRATEGY_INJECT_TOKEN: 'ACCESS_TOKEN_STRATEGY_INJECT_TOKEN',
  ACCESS_TOKEN_SECRET: '1213131313133ZVSbSbZSxdfbdsbsnbsnsnbsn',
  REFRESH_TOKEN_STRATEGY_INJECT_TOKEN: 'REFRESH_TOKEN_STRATEGY_INJECT_TOKEN',
  REFRESH_TOKEN_SECRET: 'XZDSGASG1314dsvvszbdzbzdnxnxdgndxnf'
};
